package com.streamvault.domain.util

import java.text.Normalizer
import java.util.Locale

/**
 * A single historical Brazilian telenovela record.
 *
 * @param title Original title as broadcast.
 * @param network Broadcaster that aired the novela (e.g. "TV Globo", "SBT").
 * @param year Year the novela premiered, when known.
 */
data class NovelaEntry(
    val title: String,
    val network: String,
    val year: Int?
)

/**
 * Reference catalog of Brazilian telenovelas across the major broadcasters that have
 * produced them — TV Tupi, TV Excelsior, TV Record, Rede Bandeirantes, Rede Manchete,
 * TV Cultura, SBT and TV Globo — compiled from publicly documented broadcast history.
 *
 * This lets the app recognise telenovela titles coming from IPTV/EPG/VOD sources
 * (which are often inconsistently formatted) so they can be flagged, grouped, or
 * boosted in search regardless of how a given provider labels them.
 *
 * Generated from the project's `content/novelas/*.md` reference lists — see that
 * folder to add or correct entries, then regenerate this file.
 */
object BrazilianNovelaCatalog {

    val entries: List<NovelaEntry> = listOf(
        // TV Tupi (1951–1980)
        NovelaEntry("Sua Vida me Pertence", "TV Tupi", 1951),
        NovelaEntry("Alma Cigana", "TV Tupi", 1964),
        NovelaEntry("A Gata", "TV Tupi", 1964),
        NovelaEntry("Se o Mar Contasse", "TV Tupi", 1964),
        NovelaEntry("O Segredo de Laura", "TV Tupi", 1964),
        NovelaEntry("Quando o Amor é Mais Forte", "TV Tupi", 1964),
        NovelaEntry("Quem Casa com Maria?", "TV Tupi", 1964),
        NovelaEntry("O Acusador", "TV Tupi", 1964),
        NovelaEntry("O Sorriso de Helena", "TV Tupi", 1964),
        NovelaEntry("O Direito de Nascer", "TV Tupi", 1964),
        NovelaEntry("Gutierritos, o Drama dos Humildes", "TV Tupi", 1964),
        NovelaEntry("Estrada do Pecado", "TV Tupi", 1965),
        NovelaEntry("Teresa", "TV Tupi", 1965),
        NovelaEntry("O Mestiço", "TV Tupi", 1965),
        NovelaEntry("O Cara Suja", "TV Tupi", 1965),
        NovelaEntry("Olhos que Amei", "TV Tupi", 1965),
        NovelaEntry("A Outra", "TV Tupi", 1965),
        NovelaEntry("A Cor da Sua Pele", "TV Tupi", 1965),
        NovelaEntry("O Preço de Uma Vida", "TV Tupi", 1965),
        NovelaEntry("Fatalidade", "TV Tupi", 1965),
        NovelaEntry("O Pecado de Cada Um", "TV Tupi", 1965),
        NovelaEntry("Um Rosto Perdido", "TV Tupi", 1965),
        NovelaEntry("Ana Maria, Meu Amor", "TV Tupi", 1965),
        NovelaEntry("Calúnia", "TV Tupi", 1966),
        NovelaEntry("A Inimiga", "TV Tupi", 1966),
        NovelaEntry("Somos Todos Irmãos", "TV Tupi", 1966),
        NovelaEntry("A Ré Misteriosa", "TV Tupi", 1966),
        NovelaEntry("Ciúmes", "TV Tupi", 1966),
        NovelaEntry("A Família Pimenta", "TV Tupi", 1966),
        NovelaEntry("Os Irmãos Corsos", "TV Tupi", 1966),
        NovelaEntry("O Anjo e o Vagabundo", "TV Tupi", 1966),
        NovelaEntry("Angústia de Amar", "TV Tupi", 1967),
        NovelaEntry("Yoshico, um Poema de Amor", "TV Tupi", 1967),
        NovelaEntry("A Intrusa", "TV Tupi", 1967),
        NovelaEntry("Meu Filho, Minha Vida", "TV Tupi", 1967),
        NovelaEntry("A Ponte de Waterloo", "TV Tupi", 1967),
        NovelaEntry("O Jardineiro Espanhol", "TV Tupi", 1967),
        NovelaEntry("Paixão Proibida", "TV Tupi", 1967),
        NovelaEntry("Éramos Seis", "TV Tupi", 1967),
        NovelaEntry("O Pequeno Lorde", "TV Tupi", 1967),
        NovelaEntry("A Hora Marcada", "TV Tupi", 1967),
        NovelaEntry("Encontro com o Passado", "TV Tupi", 1967),
        NovelaEntry("Presídio de Mulheres", "TV Tupi", 1967),
        NovelaEntry("Os Rebeldes", "TV Tupi", 1967),
        NovelaEntry("Estrelas no Chão", "TV Tupi", 1967),
        NovelaEntry("O Décimo Mandamento", "TV Tupi", 1968),
        NovelaEntry("Amor Sem Deus", "TV Tupi", 1968),
        NovelaEntry("Os Amores de Bob", "TV Tupi", 1968),
        NovelaEntry("O Homem que Sonhava Colorido", "TV Tupi", 1968),
        NovelaEntry("O Rouxinol da Galileia", "TV Tupi", 1968),
        NovelaEntry("O Coração Não Envelhece", "TV Tupi", 1968),
        NovelaEntry("Antônio Maria", "TV Tupi", 1968),
        NovelaEntry("Sozinho no Mundo", "TV Tupi", 1968),
        NovelaEntry("Beto Rockfeller", "TV Tupi", 1968),
        NovelaEntry("O Retrato de Laura", "TV Tupi", 1969),
        NovelaEntry("Um Gosto Amargo de Festa", "TV Tupi", 1969),
        NovelaEntry("O Doce Mundo de Guida", "TV Tupi", 1969),
        NovelaEntry("Nino, o Italianinho", "TV Tupi", 1969),
        NovelaEntry("Enquanto Houver Estrelas", "TV Tupi", 1969),
        NovelaEntry("Nenhum Homem é Deus", "TV Tupi", 1969),
        NovelaEntry("Super Plá", "TV Tupi", 1969),
        NovelaEntry("João Juca Jr.", "TV Tupi", 1970),
        NovelaEntry("E Nós, Aonde Vamos?", "TV Tupi", 1970),
        NovelaEntry("A Gordinha", "TV Tupi", 1970),
        NovelaEntry("As Bruxas", "TV Tupi", 1970),
        NovelaEntry("Simplesmente Maria", "TV Tupi", 1970),
        NovelaEntry("Toninho on the Rocks", "TV Tupi", 1970),
        NovelaEntry("O Meu Pé de Laranja Lima", "TV Tupi", 1970),
        NovelaEntry("A Selvagem", "TV Tupi", 1971),
        NovelaEntry("A Fábrica", "TV Tupi", 1971),
        NovelaEntry("Hospital", "TV Tupi", 1971),
        NovelaEntry("Nossa Filha Gabriela", "TV Tupi", 1971),
        NovelaEntry("O Preço de Um Homem", "TV Tupi", 1971),
        NovelaEntry("Signo da Esperança", "TV Tupi", 1972),
        NovelaEntry("Na Idade do Lobo", "TV Tupi", 1972),
        NovelaEntry("Bel-Ami", "TV Tupi", 1972),
        NovelaEntry("Vitória Bonelli", "TV Tupi", 1972),
        NovelaEntry("Camomila e Bem-me-quer", "TV Tupi", 1972),
        NovelaEntry("A Revolta dos Anjos", "TV Tupi", 1972),
        NovelaEntry("Tempo de Viver", "TV Tupi", 1972),
        NovelaEntry("Mulheres de Areia", "TV Tupi", 1973),
        NovelaEntry("A Volta de Beto Rockfeller", "TV Tupi", 1973),
        NovelaEntry("Rosa dos Ventos", "TV Tupi", 1973),
        NovelaEntry("O Conde Zebra", "TV Tupi", 1973),
        NovelaEntry("As Divinas… e Maravilhosas", "TV Tupi", 1973),
        NovelaEntry("Os Inocentes", "TV Tupi", 1974),
        NovelaEntry("O Machão", "TV Tupi", 1974),
        NovelaEntry("A Barba Azul", "TV Tupi", 1974),
        NovelaEntry("Ídolo de Pano", "TV Tupi", 1974),
        NovelaEntry("Meu Rico Português", "TV Tupi", 1975),
        NovelaEntry("O Velho, o Menino e o Burro", "TV Tupi", 1975),
        NovelaEntry("O Sheik de Ipanema", "TV Tupi", 1975),
        NovelaEntry("Ovelha Negra", "TV Tupi", 1975),
        NovelaEntry("Vila do Arco", "TV Tupi", 1975),
        NovelaEntry("Um Dia o Amor", "TV Tupi", 1975),
        NovelaEntry("A Viagem", "TV Tupi", 1975),
        NovelaEntry("Canção para Isabel", "TV Tupi", 1976),
        NovelaEntry("Xeque-Mate", "TV Tupi", 1976),
        NovelaEntry("Papai Coração", "TV Tupi", 1976),
        NovelaEntry("Os Apóstolos de Judas", "TV Tupi", 1976),
        NovelaEntry("O Julgamento", "TV Tupi", 1976),
        NovelaEntry("Tchan, a Grande Sacada", "TV Tupi", 1976),
        NovelaEntry("Um Sol Maior", "TV Tupi", 1977),
        NovelaEntry("Cinderela 77", "TV Tupi", 1977),
        NovelaEntry("Éramos Seis", "TV Tupi", 1977),
        NovelaEntry("O Profeta", "TV Tupi", 1977),
        NovelaEntry("João Brasileiro, o Bom Baiano", "TV Tupi", 1978),
        NovelaEntry("Roda de Fogo", "TV Tupi", 1978),
        NovelaEntry("O Direito de Nascer", "TV Tupi", 1978),
        NovelaEntry("Salário Mínimo", "TV Tupi", 1978),
        NovelaEntry("Aritana", "TV Tupi", 1978),
        NovelaEntry("Gaivotas", "TV Tupi", 1979),
        NovelaEntry("Como Salvar Meu Casamento", "TV Tupi", 1979),
        NovelaEntry("Dinheiro Vivo", "TV Tupi", 1979),
        NovelaEntry("Drácula", "TV Tupi", 1980),
        NovelaEntry("Maria Nazaré", "TV Tupi", 1980),

        // TV Excelsior (1963–1970)
        NovelaEntry("2-5499 Ocupado", "TV Excelsior", 1963),
        NovelaEntry("Aqueles que Dizem Amar-se", "TV Excelsior", 1963),
        NovelaEntry("Corações em Conflito", "TV Excelsior", 1963),
        NovelaEntry("As Solteiras", "TV Excelsior", 1964),
        NovelaEntry("Ambição", "TV Excelsior", 1964),
        NovelaEntry("A Moça que Veio de Longe", "TV Excelsior", 1964),
        NovelaEntry("Mãe", "TV Excelsior", 1964),
        NovelaEntry("A Outra Face de Anita", "TV Excelsior", 1964),
        NovelaEntry("Pecado de Mulher", "TV Excelsior", 1964),
        NovelaEntry("Folhas ao Vento", "TV Excelsior", 1964),
        NovelaEntry("É Proibido Amar", "TV Excelsior", 1964),
        NovelaEntry("Uma Sombra em Minha Vida", "TV Excelsior", 1964),
        NovelaEntry("Ilsa", "TV Excelsior", 1964),
        NovelaEntry("Melodia Fatal", "TV Excelsior", 1964),
        NovelaEntry("O Pintor e a Florista", "TV Excelsior", 1964),
        NovelaEntry("A Menina das Flores", "TV Excelsior", 1965),
        NovelaEntry("Onde Nasce a Ilusão", "TV Excelsior", 1965),
        NovelaEntry("Eu Quero Você", "TV Excelsior", 1965),
        NovelaEntry("O Céu é de Todos", "TV Excelsior", 1965),
        NovelaEntry("A Ilha dos Sonhos Perdidos", "TV Excelsior", 1965),
        NovelaEntry("A Indomável", "TV Excelsior", 1965),
        NovelaEntry("Ainda Resta Uma Esperança", "TV Excelsior", 1965),
        NovelaEntry("Ontem, Hoje e Sempre", "TV Excelsior", 1965),
        NovelaEntry("Vidas Cruzadas", "TV Excelsior", 1965),
        NovelaEntry("Pedra Redonda, 39", "TV Excelsior", 1965),
        NovelaEntry("Os Quatro Filhos", "TV Excelsior", 1965),
        NovelaEntry("Aquele que Deve Voltar", "TV Excelsior", 1965),
        NovelaEntry("A Deusa Vencida", "TV Excelsior", 1965),
        NovelaEntry("O Caminho das Estrelas", "TV Excelsior", 1965),
        NovelaEntry("Em Busca da Felicidade", "TV Excelsior", 1965),
        NovelaEntry("A Grande Viagem", "TV Excelsior", 1965),
        NovelaEntry("A Pequena Karen", "TV Excelsior", 1966),
        NovelaEntry("Almas de Pedra", "TV Excelsior", 1966),
        NovelaEntry("Redenção", "TV Excelsior", 1966),
        NovelaEntry("Anjo Marcado", "TV Excelsior", 1966),
        NovelaEntry("Ninguém Crê em Mim", "TV Excelsior", 1966),
        NovelaEntry("Abnegação", "TV Excelsior", 1966),
        NovelaEntry("As Minas de Prata", "TV Excelsior", 1966),
        NovelaEntry("O Morro dos Ventos Uivantes", "TV Excelsior", 1967),
        NovelaEntry("O Grande Segredo", "TV Excelsior", 1967),
        NovelaEntry("Os Fantoches", "TV Excelsior", 1967),
        NovelaEntry("O Tempo e o Vento", "TV Excelsior", 1967),
        NovelaEntry("Sublime Amor", "TV Excelsior", 1967),
        NovelaEntry("O Terceiro Pecado", "TV Excelsior", 1968),
        NovelaEntry("O Direito dos Filhos", "TV Excelsior", 1968),
        NovelaEntry("Legião dos Esquecidos", "TV Excelsior", 1968),
        NovelaEntry("A Pequena Órfã", "TV Excelsior", 1968),
        NovelaEntry("A Muralha", "TV Excelsior", 1968),
        NovelaEntry("Os Diabólicos", "TV Excelsior", 1968),
        NovelaEntry("Sangue do Meu Sangue", "TV Excelsior", 1969),
        NovelaEntry("Vidas em Conflito", "TV Excelsior", 1969),
        NovelaEntry("Os Estranhos", "TV Excelsior", 1969),
        NovelaEntry("A Menina do Veleiro Azul", "TV Excelsior", 1969),
        NovelaEntry("Dez Vidas", "TV Excelsior", 1969),
        NovelaEntry("Mais Forte que o Ódio", "TV Excelsior", 1970),
        NovelaEntry("A Mansão dos Vampiros", "TV Excelsior", 1970),

        // TV Record
        NovelaEntry("João Pão", "TV Record", 1964),
        NovelaEntry("Sonho de Amor", "TV Record", 1964),
        NovelaEntry("Renúncia", "TV Record", 1964),
        NovelaEntry("O Desconhecido", "TV Record", 1964),
        NovelaEntry("Banzo", "TV Record", 1964),
        NovelaEntry("Prisioneiro de um Sonho", "TV Record", 1964),
        NovelaEntry("Marcados pelo Amor", "TV Record", 1964),
        NovelaEntry("Somos Todos Irmãos", "TV Record", 1965),
        NovelaEntry("Quatro Homens Juntos", "TV Record", 1965),
        NovelaEntry("Comédia Carioca", "TV Record", 1965),
        NovelaEntry("O Segredo de Ana Maria", "TV Record", 1965),
        NovelaEntry("Turbilhão", "TV Record", 1965),
        NovelaEntry("Ceará Contra 007", "TV Record", 1965),
        NovelaEntry("Quem Bate", "TV Record", 1965),
        NovelaEntry("Mãos ao Ar", "TV Record", 1965),
        NovelaEntry("A Última Testemunha", "TV Record", 1968),
        NovelaEntry("As Professorinhas", "TV Record", 1968),
        NovelaEntry("Ana", "TV Record", 1968),
        NovelaEntry("Os Acorrentados", "TV Record", 1969),
        NovelaEntry("Algemas de Ouro", "TV Record", 1969),
        NovelaEntry("Seu Único Pecado", "TV Record", 1969),
        NovelaEntry("As Pupilas do Senhor Reitor", "TV Record", 1970),
        NovelaEntry("Tilim", "TV Record", 1970),
        NovelaEntry("O Príncipe e o Mendigo", "TV Record", 1971),
        NovelaEntry("Os Deuses Estão Mortos", "TV Record", 1971),
        NovelaEntry("Editora Mayo, Bom Dia", "TV Record", 1971),
        NovelaEntry("Pingo de Gente", "TV Record", 1971),
        NovelaEntry("Sol Amarelo", "TV Record", 1971),
        NovelaEntry("Quarenta Anos Depois", "TV Record", 1971),
        NovelaEntry("O Tempo Não Apaga", "TV Record", 1972),
        NovelaEntry("Os Fidalgos da Casa Mourisca", "TV Record", 1972),
        NovelaEntry("O Leopardo", "TV Record", 1972),
        NovelaEntry("Eu e a Moto", "TV Record", 1972),
        NovelaEntry("Quero Viver", "TV Record", 1972),
        NovelaEntry("Vendaval", "TV Record", 1973),
        NovelaEntry("Venha Ver o Sol na Estrada", "TV Record", 1973),
        NovelaEntry("Vidas Marcadas", "TV Record", 1973),
        NovelaEntry("Meu Adorável Mendigo", "TV Record", 1973),
        NovelaEntry("O Espantalho", "TV Record", 1977),
        NovelaEntry("Direito de Vencer", "TV Record", 1997),
        NovelaEntry("Canoa do Bagre", "TV Record", 1997),
        NovelaEntry("Janela para o Céu", "TV Record", 1997),
        NovelaEntry("Velas de Sangue", "TV Record", 1997),
        NovelaEntry("A Sétima Bala", "TV Record", 1997),
        NovelaEntry("Do Fundo do Coração", "TV Record", 1998),
        NovelaEntry("Estrela de Fogo", "TV Record", 1998),
        NovelaEntry("Louca Paixão", "TV Record", 1999),
        NovelaEntry("Tiro e Queda", "TV Record", 1999),
        NovelaEntry("Marcas da Paixão", "TV Record", 2000),
        NovelaEntry("Vidas Cruzadas", "TV Record", 2000),
        NovelaEntry("Roda da Vida", "TV Record", 2001),
        NovelaEntry("Metamorphoses", "TV Record", 2004),
        NovelaEntry("A Escrava Isaura", "TV Record", 2004),
        NovelaEntry("Essas Mulheres", "TV Record", 2005),
        NovelaEntry("Prova de Amor", "TV Record", 2005),
        NovelaEntry("Cidadão Brasileiro", "TV Record", 2006),
        NovelaEntry("Bicho do Mato", "TV Record", 2006),
        NovelaEntry("Alta Estação", "TV Record", 2006),
        NovelaEntry("Vidas Opostas", "TV Record", 2006),
        NovelaEntry("Luz do Sol", "TV Record", 2007),
        NovelaEntry("Os Mutantes – Caminhos do Coração", "TV Record", 2007),
        NovelaEntry("Amor e Intrigas", "TV Record", 2007),
        NovelaEntry("Chamas da Vida", "TV Record", 2008),
        NovelaEntry("Promessas de Amor", "TV Record", 2009),
        NovelaEntry("Poder Paralelo", "TV Record", 2009),
        NovelaEntry("Bela, a Feia", "TV Record", 2009),
        NovelaEntry("Ribeirão do Tempo", "TV Record", 2010),
        NovelaEntry("Rebelde", "TV Record", 2011),
        NovelaEntry("Vidas em Jogo", "TV Record", 2011),
        NovelaEntry("Máscaras", "TV Record", 2012),
        NovelaEntry("Balacobaco", "TV Record", 2012),
        NovelaEntry("Dona Xepa", "TV Record", 2013),
        NovelaEntry("Pecado Mortal", "TV Record", 2013),
        NovelaEntry("Vitória", "TV Record", 2014),
        NovelaEntry("Os Dez Mandamentos", "TV Record", 2015),
        NovelaEntry("Escrava Mãe", "TV Record", 2016),
        NovelaEntry("A Terra Prometida", "TV Record", 2016),
        NovelaEntry("O Rico e Lázaro", "TV Record", 2017),
        NovelaEntry("Belaventura", "TV Record", 2017),
        NovelaEntry("Apocalipse", "TV Record", 2017),
        NovelaEntry("Jesus", "TV Record", 2018),
        NovelaEntry("Jezabel", "TV Record", 2019),
        NovelaEntry("Topíssima", "TV Record", 2019),
        NovelaEntry("Amor sem Igual", "TV Record", 2019),
        NovelaEntry("Gênesis", "TV Record", 2021),
        NovelaEntry("Reis", "TV Record", 2022),
        NovelaEntry("Paulo, o Apóstolo", "TV Record", 2025),
        NovelaEntry("A Vida de Jó", "TV Record", 2025),
        NovelaEntry("O Senhor e a Serva", "TV Record", 2025),
        NovelaEntry("Ben-Hur", "TV Record", 2026),
        NovelaEntry("As Sete Marias", "TV Record", 2026),
        NovelaEntry("Amor em Ruínas", "TV Record", 2026),

        // Rede Bandeirantes (1967–presente)
        NovelaEntry("Os Miseráveis", "Rede Bandeirantes", 1967),
        NovelaEntry("A Moça do Sobrado Grande", "Rede Bandeirantes", 1967),
        NovelaEntry("Ricardinho, Sou Criança, Quero Viver", "Rede Bandeirantes", 1968),
        NovelaEntry("Nunca é Tarde Demais", "Rede Bandeirantes", 1968),
        NovelaEntry("Era Preciso Voltar", "Rede Bandeirantes", 1969),
        NovelaEntry("O Bolha", "Rede Bandeirantes", 1969),
        NovelaEntry("As Asas São para Voar", "Rede Bandeirantes", 1970),
        NovelaEntry("Cara a Cara", "Rede Bandeirantes", 1979),
        NovelaEntry("O Todo-Poderoso", "Rede Bandeirantes", 1979),
        NovelaEntry("Pé de Vento", "Rede Bandeirantes", 1980),
        NovelaEntry("A Deusa Vencida", "Rede Bandeirantes", 1980),
        NovelaEntry("Cavalo Amarelo", "Rede Bandeirantes", 1980),
        NovelaEntry("Um Homem Muito Especial", "Rede Bandeirantes", 1980),
        NovelaEntry("O Meu Pé de Laranja Lima", "Rede Bandeirantes", 1980),
        NovelaEntry("Dulcinéa Vai à Guerra", "Rede Bandeirantes", 1980),
        NovelaEntry("Rosa Baiana", "Rede Bandeirantes", 1981),
        NovelaEntry("Os Imigrantes", "Rede Bandeirantes", 1981),
        NovelaEntry("Os Adolescentes", "Rede Bandeirantes", 1981),
        NovelaEntry("Ninho da Serpente", "Rede Bandeirantes", 1982),
        NovelaEntry("A Filha do Silêncio", "Rede Bandeirantes", 1982),
        NovelaEntry("Renúncia", "Rede Bandeirantes", 1982),
        NovelaEntry("Campeão", "Rede Bandeirantes", 1982),
        NovelaEntry("Sabor de Mel", "Rede Bandeirantes", 1983),
        NovelaEntry("Braço de Ferro", "Rede Bandeirantes", 1983),
        NovelaEntry("Maçã do Amor", "Rede Bandeirantes", 1983),
        NovelaEntry("A Idade da Loba", "Rede Bandeirantes", 1995),
        NovelaEntry("O Campeão", "Rede Bandeirantes", 1996),
        NovelaEntry("Perdidos de Amor", "Rede Bandeirantes", 1996),
        NovelaEntry("Serras Azuis", "Rede Bandeirantes", 1998),
        NovelaEntry("Meu Pé de Laranja Lima", "Rede Bandeirantes", 1998),
        NovelaEntry("Floribella", "Rede Bandeirantes", 2005),
        NovelaEntry("Floribella", "Rede Bandeirantes", 2006),
        NovelaEntry("Paixões Proibidas", "Rede Bandeirantes", 2006),
        NovelaEntry("Dance Dance Dance", "Rede Bandeirantes", 2007),
        NovelaEntry("Água na Boca", "Rede Bandeirantes", 2008),
        NovelaEntry("Beleza Fatal", "Rede Bandeirantes", 2025),
        NovelaEntry("Dona Beja — tentativa recente da Band de retomar a teledramaturgia própria", "Rede Bandeirantes", 2025),

        // Rede Manchete (1985–1999)
        NovelaEntry("Antônio Maria", "Rede Manchete", 1985),
        NovelaEntry("Dona Beija", "Rede Manchete", 1986),
        NovelaEntry("Novo Amor", "Rede Manchete", 1986),
        NovelaEntry("Tudo ou Nada", "Rede Manchete", 1986),
        NovelaEntry("Mania de Querer", "Rede Manchete", 1986),
        NovelaEntry("Corpo Santo", "Rede Manchete", 1987),
        NovelaEntry("Helena", "Rede Manchete", 1987),
        NovelaEntry("Carmem", "Rede Manchete", 1987),
        NovelaEntry("Olho por Olho", "Rede Manchete", 1988),
        NovelaEntry("Kananga do Japão", "Rede Manchete", 1989),
        NovelaEntry("Pantanal", "Rede Manchete", 1990),
        NovelaEntry("A História de Ana Raio e Zé Trovão", "Rede Manchete", 1990),
        NovelaEntry("Amazônia", "Rede Manchete", 1991),
        NovelaEntry("Guerra sem Fim", "Rede Manchete", 1993),
        NovelaEntry("74.5 – Uma Onda no Ar", "Rede Manchete", 1994),
        NovelaEntry("Tocaia Grande", "Rede Manchete", 1995),
        NovelaEntry("Xica da Silva", "Rede Manchete", 1996),
        NovelaEntry("Mandacaru", "Rede Manchete", 1997),
        NovelaEntry("Brida", "Rede Manchete", 1998),

        // TV Cultura (1965–1971)
        NovelaEntry("Escrava do Silêncio", "TV Cultura", 1965),
        NovelaEntry("As Professorinhas", "TV Cultura", 1965),
        NovelaEntry("Amor de Perdição", "TV Cultura", 1965),
        NovelaEntry("O Moço Loiro", "TV Cultura", 1965),
        NovelaEntry("O Tirano", "TV Cultura", 1965),
        NovelaEntry("Sangue Rebelde", "TV Cultura", 1966),
        NovelaEntry("Meu Pedacinho de Chão", "TV Cultura", 1971),

        // SBT (1981–2024)
        NovelaEntry("Destino", "SBT", 1982),
        NovelaEntry("A Força do Amor", "SBT", 1982),
        NovelaEntry("A Leoa", "SBT", 1982),
        NovelaEntry("Conflito", "SBT", 1982),
        NovelaEntry("Sombras do Passado", "SBT", 1983),
        NovelaEntry("Acorrentada", "SBT", 1983),
        NovelaEntry("A Ponte do Amor", "SBT", 1983),
        NovelaEntry("A Justiça de Deus", "SBT", 1983),
        NovelaEntry("Pecado de Amor", "SBT", 1983),
        NovelaEntry("Razão de Viver", "SBT", 1983),
        NovelaEntry("O Anjo Maldito", "SBT", 1983),
        NovelaEntry("Vida Roubada", "SBT", 1983),
        NovelaEntry("Meus Filhos, Minha Vida", "SBT", 1984),
        NovelaEntry("Jerônimo", "SBT", 1984),
        NovelaEntry("Jogo do Amor", "SBT", 1985),
        NovelaEntry("Uma Esperança no Ar", "SBT", 1985),
        NovelaEntry("Cortina de Vidro", "SBT", 1989),
        NovelaEntry("Brasileiras e Brasileiros", "SBT", 1990),
        NovelaEntry("Éramos Seis", "SBT", 1994),
        NovelaEntry("As Pupilas do Senhor Reitor", "SBT", 1994),
        NovelaEntry("Sangue do Meu Sangue", "SBT", 1995),
        NovelaEntry("Colégio Brasil", "SBT", 1996),
        NovelaEntry("Antônio Alves, Taxista", "SBT", 1996),
        NovelaEntry("Razão de Viver", "SBT", 1996),
        NovelaEntry("Dona Anja", "SBT", 1996),
        NovelaEntry("Os Ossos do Barão", "SBT", 1997),
        NovelaEntry("Chiquititas", "SBT", 1997),
        NovelaEntry("Fascinação", "SBT", 1998),
        NovelaEntry("Pérola Negra", "SBT", 1998),
        NovelaEntry("O Direito de Nascer", "SBT", 2001),
        NovelaEntry("Pícara Sonhadora", "SBT", 2001),
        NovelaEntry("Amor e Ódio", "SBT", 2001),
        NovelaEntry("Marisol", "SBT", 2002),
        NovelaEntry("Pequena Travessa", "SBT", 2002),
        NovelaEntry("Jamais Te Esquecerei", "SBT", 2003),
        NovelaEntry("Canavial de Paixões", "SBT", 2003),
        NovelaEntry("Seus Olhos", "SBT", 2004),
        NovelaEntry("Esmeralda", "SBT", 2004),
        NovelaEntry("Os Ricos Também Choram", "SBT", 2005),
        NovelaEntry("Cristal", "SBT", 2006),
        NovelaEntry("Maria Esperança", "SBT", 2007),
        NovelaEntry("Amigas e Rivais", "SBT", 2007),
        NovelaEntry("Revelação", "SBT", 2008),
        NovelaEntry("Vende-se um Véu de Noiva", "SBT", 2009),
        NovelaEntry("Uma Rosa com Amor", "SBT", 2010),
        NovelaEntry("Amor e Revolução", "SBT", 2011),
        NovelaEntry("Corações Feridos", "SBT", 2012),
        NovelaEntry("Carrossel", "SBT", 2012),
        NovelaEntry("Chiquititas", "SBT", 2013),
        NovelaEntry("Cúmplices de um Resgate", "SBT", 2015),
        NovelaEntry("Carinha de Anjo", "SBT", 2016),
        NovelaEntry("As Aventuras de Poliana", "SBT", 2018),
        NovelaEntry("Poliana Moça", "SBT", 2022),
        NovelaEntry("A Infância de Romeu e Julieta", "SBT", 2023),
        NovelaEntry("A Caverna Encantada", "SBT", 2024),

        // TV Globo (1965–2026)
        NovelaEntry("Ilusões Perdidas", "TV Globo", 1965),
        NovelaEntry("Rosinha do Sobrado", "TV Globo", 1965),
        NovelaEntry("Marina", "TV Globo", 1965),
        NovelaEntry("Paixão de Outono", "TV Globo", 1965),
        NovelaEntry("A Moreninha", "TV Globo", 1965),
        NovelaEntry("O Ébrio", "TV Globo", 1965),
        NovelaEntry("Um Rosto de Mulher", "TV Globo", 1965),
        NovelaEntry("Padre Tião", "TV Globo", 1965),
        NovelaEntry("Eu Compro Essa Mulher", "TV Globo", 1966),
        NovelaEntry("O Sheik de Agadir", "TV Globo", 1966),
        NovelaEntry("O Rei dos Ciganos", "TV Globo", 1966),
        NovelaEntry("A Rainha Louca", "TV Globo", 1967),
        NovelaEntry("A Sombra de Rebeca", "TV Globo", 1967),
        NovelaEntry("Anastácia, a Mulher sem Destino", "TV Globo", 1967),
        NovelaEntry("O Homem Proibido", "TV Globo", 1967),
        NovelaEntry("Sangue e Areia", "TV Globo", 1967),
        NovelaEntry("O Santo Mestiço", "TV Globo", 1968),
        NovelaEntry("A Grande Mentira", "TV Globo", 1968),
        NovelaEntry("Passo dos Ventos", "TV Globo", 1968),
        NovelaEntry("A Gata de Vison", "TV Globo", 1968),
        NovelaEntry("A Última Valsa", "TV Globo", 1969),
        NovelaEntry("Rosa Rebelde", "TV Globo", 1969),
        NovelaEntry("A Ponte dos Suspiros", "TV Globo", 1969),
        NovelaEntry("A Cabana do Pai Tomás", "TV Globo", 1969),
        NovelaEntry("Véu de Noiva", "TV Globo", 1969),
        NovelaEntry("Verão Vermelho", "TV Globo", 1969),
        NovelaEntry("Pigmalião 70", "TV Globo", 1970),
        NovelaEntry("Irmãos Coragem", "TV Globo", 1970),
        NovelaEntry("Assim na Terra Como no Céu", "TV Globo", 1970),
        NovelaEntry("A Próxima Atração", "TV Globo", 1970),
        NovelaEntry("O Cafona", "TV Globo", 1971),
        NovelaEntry("Minha Doce Namorada", "TV Globo", 1971),
        NovelaEntry("O Homem que Deve Morrer", "TV Globo", 1971),
        NovelaEntry("Meu Pedacinho de Chão", "TV Globo", 1971),
        NovelaEntry("Bandeira Dois", "TV Globo", 1971),
        NovelaEntry("O Primeiro Amor", "TV Globo", 1972),
        NovelaEntry("Selva de Pedra", "TV Globo", 1972),
        NovelaEntry("Bicho do Mato", "TV Globo", 1972),
        NovelaEntry("O Bofe", "TV Globo", 1972),
        NovelaEntry("Uma Rosa com Amor", "TV Globo", 1972),
        NovelaEntry("A Patota", "TV Globo", 1972),
        NovelaEntry("Cavalo de Aço", "TV Globo", 1973),
        NovelaEntry("O Bem-Amado", "TV Globo", 1973),
        NovelaEntry("Carinhoso", "TV Globo", 1973),
        NovelaEntry("O Semideus", "TV Globo", 1973),
        NovelaEntry("Os Ossos do Barão", "TV Globo", 1973),
        NovelaEntry("Supermanoela", "TV Globo", 1974),
        NovelaEntry("O Espigão", "TV Globo", 1974),
        NovelaEntry("Fogo sobre Terra", "TV Globo", 1974),
        NovelaEntry("João da Silva", "TV Globo", 1974),
        NovelaEntry("Corrida do Ouro", "TV Globo", 1974),
        NovelaEntry("O Rebu", "TV Globo", 1974),
        NovelaEntry("Escalada", "TV Globo", 1975),
        NovelaEntry("Cuca Legal", "TV Globo", 1975),
        NovelaEntry("Gabriela", "TV Globo", 1975),
        NovelaEntry("Helena", "TV Globo", 1975),
        NovelaEntry("O Noviço", "TV Globo", 1975),
        NovelaEntry("Bravo!", "TV Globo", 1975),
        NovelaEntry("Senhora", "TV Globo", 1975),
        NovelaEntry("Roque Santeiro", "TV Globo", 1975),
        NovelaEntry("A Moreninha", "TV Globo", 1975),
        NovelaEntry("O Grito", "TV Globo", 1975),
        NovelaEntry("Pecado Capital", "TV Globo", 1975),
        NovelaEntry("Anjo Mau", "TV Globo", 1976),
        NovelaEntry("Vejo a Lua no Céu", "TV Globo", 1976),
        NovelaEntry("Saramandaia", "TV Globo", 1976),
        NovelaEntry("O Casarão", "TV Globo", 1976),
        NovelaEntry("O Feijão e o Sonho", "TV Globo", 1976),
        NovelaEntry("Estúpido Cupido", "TV Globo", 1976),
        NovelaEntry("Escrava Isaura", "TV Globo", 1976),
        NovelaEntry("Duas Vidas", "TV Globo", 1976),
        NovelaEntry("Despedida de Casado", "TV Globo", 1977),
        NovelaEntry("À Sombra dos Laranjais", "TV Globo", 1977),
        NovelaEntry("Locomotivas", "TV Globo", 1977),
        NovelaEntry("Dona Xepa", "TV Globo", 1977),
        NovelaEntry("Espelho Mágico", "TV Globo", 1977),
        NovelaEntry("Coquetel de Amor", "TV Globo", 1977),
        NovelaEntry("Nina", "TV Globo", 1977),
        NovelaEntry("Sem Lenço, Sem Documento", "TV Globo", 1977),
        NovelaEntry("Sinhazinha Flô", "TV Globo", 1977),
        NovelaEntry("O Astro", "TV Globo", 1977),
        NovelaEntry("O Pulo do Gato", "TV Globo", 1978),
        NovelaEntry("Maria Maria", "TV Globo", 1978),
        NovelaEntry("Te Contei?", "TV Globo", 1978),
        NovelaEntry("Gina", "TV Globo", 1978),
        NovelaEntry("Dancin' Days", "TV Globo", 1978),
        NovelaEntry("Sinal de Alerta", "TV Globo", 1978),
        NovelaEntry("Pecado Rasgado", "TV Globo", 1978),
        NovelaEntry("A Sucessora", "TV Globo", 1978),
        NovelaEntry("Pai Herói", "TV Globo", 1979),
        NovelaEntry("Memórias de Amor", "TV Globo", 1979),
        NovelaEntry("Feijão Maravilha", "TV Globo", 1979),
        NovelaEntry("Cabocla", "TV Globo", 1979),
        NovelaEntry("Marron Glacé", "TV Globo", 1979),
        NovelaEntry("Os Gigantes", "TV Globo", 1979),
        NovelaEntry("Olhai os Lírios do Campo", "TV Globo", 1980),
        NovelaEntry("Água Viva", "TV Globo", 1980),
        NovelaEntry("Chega Mais", "TV Globo", 1980),
        NovelaEntry("Marina", "TV Globo", 1980),
        NovelaEntry("Coração Alado", "TV Globo", 1980),
        NovelaEntry("Plumas e Paetês", "TV Globo", 1980),
        NovelaEntry("As Três Marias", "TV Globo", 1980),
        NovelaEntry("Baila Comigo", "TV Globo", 1981),
        NovelaEntry("O Amor é Nosso!", "TV Globo", 1981),
        NovelaEntry("Ciranda de Pedra", "TV Globo", 1981),
        NovelaEntry("Brilhante", "TV Globo", 1981),
        NovelaEntry("Jogo da Vida", "TV Globo", 1981),
        NovelaEntry("Terras do Sem Fim", "TV Globo", 1981),
        NovelaEntry("O Homem Proibido", "TV Globo", 1982),
        NovelaEntry("Sétimo Sentido", "TV Globo", 1982),
        NovelaEntry("Elas por Elas", "TV Globo", 1982),
        NovelaEntry("Paraíso", "TV Globo", 1982),
        NovelaEntry("Sol de Verão", "TV Globo", 1982),
        NovelaEntry("Final Feliz", "TV Globo", 1982),
        NovelaEntry("Pão Pão, Beijo Beijo", "TV Globo", 1983),
        NovelaEntry("Louco Amor", "TV Globo", 1983),
        NovelaEntry("Guerra dos Sexos", "TV Globo", 1983),
        NovelaEntry("Eu Prometo", "TV Globo", 1983),
        NovelaEntry("Voltei pra Você", "TV Globo", 1983),
        NovelaEntry("Champagne", "TV Globo", 1983),
        NovelaEntry("Transas e Caretas", "TV Globo", 1984),
        NovelaEntry("Amor com Amor se Paga", "TV Globo", 1984),
        NovelaEntry("Partido Alto", "TV Globo", 1984),
        NovelaEntry("Vereda Tropical", "TV Globo", 1984),
        NovelaEntry("Livre para Voar", "TV Globo", 1984),
        NovelaEntry("Corpo a Corpo", "TV Globo", 1984),
        NovelaEntry("Um Sonho a Mais", "TV Globo", 1985),
        NovelaEntry("A Gata Comeu", "TV Globo", 1985),
        NovelaEntry("Roque Santeiro", "TV Globo", 1985),
        NovelaEntry("Ti-Ti-Ti", "TV Globo", 1985),
        NovelaEntry("De Quina pra Lua", "TV Globo", 1985),
        NovelaEntry("Selva de Pedra", "TV Globo", 1986),
        NovelaEntry("Cambalacho", "TV Globo", 1986),
        NovelaEntry("Sinhá Moça", "TV Globo", 1986),
        NovelaEntry("Roda de Fogo", "TV Globo", 1986),
        NovelaEntry("Hipertensão", "TV Globo", 1986),
        NovelaEntry("Direito de Amar", "TV Globo", 1987),
        NovelaEntry("O Outro", "TV Globo", 1987),
        NovelaEntry("Brega e Chique", "TV Globo", 1987),
        NovelaEntry("Bambolê", "TV Globo", 1987),
        NovelaEntry("Mandala", "TV Globo", 1987),
        NovelaEntry("Sassaricando", "TV Globo", 1987),
        NovelaEntry("Fera Radical", "TV Globo", 1988),
        NovelaEntry("Vale Tudo", "TV Globo", 1988),
        NovelaEntry("Bebê a Bordo", "TV Globo", 1988),
        NovelaEntry("Vida Nova", "TV Globo", 1988),
        NovelaEntry("O Salvador da Pátria", "TV Globo", 1989),
        NovelaEntry("Que Rei Sou Eu?", "TV Globo", 1989),
        NovelaEntry("Pacto de Sangue", "TV Globo", 1989),
        NovelaEntry("Tieta", "TV Globo", 1989),
        NovelaEntry("Top Model", "TV Globo", 1989),
        NovelaEntry("O Sexo dos Anjos", "TV Globo", 1989),
        NovelaEntry("Gente Fina", "TV Globo", 1990),
        NovelaEntry("Rainha da Sucata", "TV Globo", 1990),
        NovelaEntry("Mico Preto", "TV Globo", 1990),
        NovelaEntry("Barriga de Aluguel", "TV Globo", 1990),
        NovelaEntry("Araponga", "TV Globo", 1990),
        NovelaEntry("Meu Bem, Meu Mal", "TV Globo", 1990),
        NovelaEntry("Lua Cheia de Amor", "TV Globo", 1990),
        NovelaEntry("O Dono do Mundo", "TV Globo", 1991),
        NovelaEntry("Salomé", "TV Globo", 1991),
        NovelaEntry("Vamp", "TV Globo", 1991),
        NovelaEntry("Felicidade", "TV Globo", 1991),
        NovelaEntry("Pedra sobre Pedra", "TV Globo", 1992),
        NovelaEntry("Perigosas Peruas", "TV Globo", 1992),
        NovelaEntry("Despedida de Solteiro", "TV Globo", 1992),
        NovelaEntry("De Corpo e Alma", "TV Globo", 1992),
        NovelaEntry("Deus Nos Acuda", "TV Globo", 1992),
        NovelaEntry("Mulheres de Areia", "TV Globo", 1993),
        NovelaEntry("Renascer", "TV Globo", 1993),
        NovelaEntry("O Mapa da Mina", "TV Globo", 1993),
        NovelaEntry("Olho no Olho", "TV Globo", 1993),
        NovelaEntry("Sonho Meu", "TV Globo", 1993),
        NovelaEntry("Fera Ferida", "TV Globo", 1993),
        NovelaEntry("A Viagem", "TV Globo", 1994),
        NovelaEntry("Tropicaliente", "TV Globo", 1994),
        NovelaEntry("Pátria Minha", "TV Globo", 1994),
        NovelaEntry("Quatro por Quatro", "TV Globo", 1994),
        NovelaEntry("Irmãos Coragem", "TV Globo", 1995),
        NovelaEntry("A Próxima Vítima", "TV Globo", 1995),
        NovelaEntry("História de Amor", "TV Globo", 1995),
        NovelaEntry("Cara e Coroa", "TV Globo", 1995),
        NovelaEntry("Explode Coração", "TV Globo", 1995),
        NovelaEntry("Quem é Você", "TV Globo", 1996),
        NovelaEntry("Vira-Lata", "TV Globo", 1996),
        NovelaEntry("O Fim do Mundo", "TV Globo", 1996),
        NovelaEntry("O Rei do Gado", "TV Globo", 1996),
        NovelaEntry("Anjo de Mim", "TV Globo", 1996),
        NovelaEntry("Salsa e Merengue", "TV Globo", 1996),
        NovelaEntry("A Indomada", "TV Globo", 1997),
        NovelaEntry("O Amor Está no Ar", "TV Globo", 1997),
        NovelaEntry("Zazá", "TV Globo", 1997),
        NovelaEntry("Anjo Mau", "TV Globo", 1997),
        NovelaEntry("Por Amor", "TV Globo", 1997),
        NovelaEntry("Corpo Dourado", "TV Globo", 1998),
        NovelaEntry("Era Uma Vez...", "TV Globo", 1998),
        NovelaEntry("Torre de Babel", "TV Globo", 1998),
        NovelaEntry("Meu Bem-Querer", "TV Globo", 1998),
        NovelaEntry("Pecado Capital", "TV Globo", 1998),
        NovelaEntry("Suave Veneno", "TV Globo", 1999),
        NovelaEntry("Andando nas Nuvens", "TV Globo", 1999),
        NovelaEntry("Força de um Desejo", "TV Globo", 1999),
        NovelaEntry("Terra Nostra", "TV Globo", 1999),
        NovelaEntry("Vila Madalena", "TV Globo", 1999),
        NovelaEntry("Esplendor", "TV Globo", 2000),
        NovelaEntry("Uga Uga", "TV Globo", 2000),
        NovelaEntry("Laços de Família", "TV Globo", 2000),
        NovelaEntry("O Cravo e a Rosa", "TV Globo", 2000),
        NovelaEntry("Um Anjo Caiu do Céu", "TV Globo", 2001),
        NovelaEntry("Porto dos Milagres", "TV Globo", 2001),
        NovelaEntry("Estrela-Guia", "TV Globo", 2001),
        NovelaEntry("A Padroeira", "TV Globo", 2001),
        NovelaEntry("As Filhas da Mãe", "TV Globo", 2001),
        NovelaEntry("O Clone", "TV Globo", 2001),
        NovelaEntry("Desejos de Mulher", "TV Globo", 2002),
        NovelaEntry("Coração de Estudante", "TV Globo", 2002),
        NovelaEntry("Esperança", "TV Globo", 2002),
        NovelaEntry("O Beijo do Vampiro", "TV Globo", 2002),
        NovelaEntry("Sabor da Paixão", "TV Globo", 2002),
        NovelaEntry("Mulheres Apaixonadas", "TV Globo", 2003),
        NovelaEntry("Agora é que São Elas", "TV Globo", 2003),
        NovelaEntry("Kubanacan", "TV Globo", 2003),
        NovelaEntry("Chocolate com Pimenta", "TV Globo", 2003),
        NovelaEntry("Celebridade", "TV Globo", 2003),
        NovelaEntry("Da Cor do Pecado", "TV Globo", 2004),
        NovelaEntry("Cabocla", "TV Globo", 2004),
        NovelaEntry("Senhora do Destino", "TV Globo", 2004),
        NovelaEntry("Começar de Novo", "TV Globo", 2004),
        NovelaEntry("Como Uma Onda", "TV Globo", 2004),
        NovelaEntry("América", "TV Globo", 2005),
        NovelaEntry("A Lua Me Disse", "TV Globo", 2005),
        NovelaEntry("Alma Gêmea", "TV Globo", 2005),
        NovelaEntry("Bang Bang", "TV Globo", 2005),
        NovelaEntry("Belíssima", "TV Globo", 2005),
        NovelaEntry("Sinhá Moça", "TV Globo", 2006),
        NovelaEntry("Cobras e Lagartos", "TV Globo", 2006),
        NovelaEntry("Páginas da Vida", "TV Globo", 2006),
        NovelaEntry("O Profeta", "TV Globo", 2006),
        NovelaEntry("Pé na Jaca", "TV Globo", 2006),
        NovelaEntry("Paraíso Tropical", "TV Globo", 2007),
        NovelaEntry("Eterna Magia", "TV Globo", 2007),
        NovelaEntry("Sete Pecados", "TV Globo", 2007),
        NovelaEntry("Duas Caras", "TV Globo", 2007),
        NovelaEntry("Desejo Proibido", "TV Globo", 2007),
        NovelaEntry("Beleza Pura", "TV Globo", 2008),
        NovelaEntry("Ciranda de Pedra", "TV Globo", 2008),
        NovelaEntry("A Favorita", "TV Globo", 2008),
        NovelaEntry("Três Irmãs", "TV Globo", 2008),
        NovelaEntry("Negócio da China", "TV Globo", 2008),
        NovelaEntry("Caminho das Índias", "TV Globo", 2009),
        NovelaEntry("Paraíso", "TV Globo", 2009),
        NovelaEntry("Caras e Bocas", "TV Globo", 2009),
        NovelaEntry("Viver a Vida", "TV Globo", 2009),
        NovelaEntry("Cama de Gato", "TV Globo", 2009),
        NovelaEntry("Tempos Modernos", "TV Globo", 2010),
        NovelaEntry("Escrito nas Estrelas", "TV Globo", 2010),
        NovelaEntry("Passione", "TV Globo", 2010),
        NovelaEntry("Ti-Ti-Ti", "TV Globo", 2010),
        NovelaEntry("Araguaia", "TV Globo", 2010),
        NovelaEntry("Insensato Coração", "TV Globo", 2011),
        NovelaEntry("Morde e Assopra", "TV Globo", 2011),
        NovelaEntry("Cordel Encantado", "TV Globo", 2011),
        NovelaEntry("O Astro", "TV Globo", 2011),
        NovelaEntry("Fina Estampa", "TV Globo", 2011),
        NovelaEntry("A Vida da Gente", "TV Globo", 2011),
        NovelaEntry("Aquele Beijo", "TV Globo", 2011),
        NovelaEntry("Amor Eterno Amor", "TV Globo", 2012),
        NovelaEntry("Avenida Brasil", "TV Globo", 2012),
        NovelaEntry("Cheias de Charme", "TV Globo", 2012),
        NovelaEntry("Gabriela", "TV Globo", 2012),
        NovelaEntry("Lado a Lado", "TV Globo", 2012),
        NovelaEntry("Guerra dos Sexos", "TV Globo", 2012),
        NovelaEntry("Salve Jorge", "TV Globo", 2012),
        NovelaEntry("Flor do Caribe", "TV Globo", 2013),
        NovelaEntry("Sangue Bom", "TV Globo", 2013),
        NovelaEntry("Amor à Vida", "TV Globo", 2013),
        NovelaEntry("Saramandaia", "TV Globo", 2013),
        NovelaEntry("Joia Rara", "TV Globo", 2013),
        NovelaEntry("Além do Horizonte", "TV Globo", 2013),
        NovelaEntry("Em Família", "TV Globo", 2014),
        NovelaEntry("Meu Pedacinho de Chão", "TV Globo", 2014),
        NovelaEntry("Geração Brasil", "TV Globo", 2014),
        NovelaEntry("O Rebu", "TV Globo", 2014),
        NovelaEntry("Império", "TV Globo", 2014),
        NovelaEntry("Boogie Oogie", "TV Globo", 2014),
        NovelaEntry("Alto Astral", "TV Globo", 2014),
        NovelaEntry("Sete Vidas", "TV Globo", 2015),
        NovelaEntry("Babilônia", "TV Globo", 2015),
        NovelaEntry("I Love Paraisópolis", "TV Globo", 2015),
        NovelaEntry("Verdades Secretas", "TV Globo", 2015),
        NovelaEntry("Além do Tempo", "TV Globo", 2015),
        NovelaEntry("A Regra do Jogo", "TV Globo", 2015),
        NovelaEntry("Totalmente Demais", "TV Globo", 2015),
        NovelaEntry("Êta Mundo Bom!", "TV Globo", 2016),
        NovelaEntry("Velho Chico", "TV Globo", 2016),
        NovelaEntry("Liberdade, Liberdade", "TV Globo", 2016),
        NovelaEntry("Haja Coração", "TV Globo", 2016),
        NovelaEntry("Sol Nascente", "TV Globo", 2016),
        NovelaEntry("A Lei do Amor", "TV Globo", 2016),
        NovelaEntry("Rock Story", "TV Globo", 2016),
        NovelaEntry("Novo Mundo", "TV Globo", 2017),
        NovelaEntry("A Força do Querer", "TV Globo", 2017),
        NovelaEntry("Os Dias Eram Assim", "TV Globo", 2017),
        NovelaEntry("Pega Pega", "TV Globo", 2017),
        NovelaEntry("Tempo de Amar", "TV Globo", 2017),
        NovelaEntry("O Outro Lado do Paraíso", "TV Globo", 2017),
        NovelaEntry("Deus Salve o Rei", "TV Globo", 2018),
        NovelaEntry("Orgulho e Paixão", "TV Globo", 2018),
        NovelaEntry("Onde Nascem os Fortes", "TV Globo", 2018),
        NovelaEntry("Segundo Sol", "TV Globo", 2018),
        NovelaEntry("O Tempo Não Para", "TV Globo", 2018),
        NovelaEntry("Espelho da Vida", "TV Globo", 2018),
        NovelaEntry("O Sétimo Guardião", "TV Globo", 2018),
        NovelaEntry("Verão 90", "TV Globo", 2019),
        NovelaEntry("Órfãos da Terra", "TV Globo", 2019),
        NovelaEntry("A Dona do Pedaço", "TV Globo", 2019),
        NovelaEntry("Bom Sucesso", "TV Globo", 2019),
        NovelaEntry("Éramos Seis", "TV Globo", 2019),
        NovelaEntry("Amor de Mãe", "TV Globo", 2019),
        NovelaEntry("Salve-se Quem Puder", "TV Globo", 2020),
        NovelaEntry("Nos Tempos do Imperador", "TV Globo", 2021),
        NovelaEntry("Verdades Secretas 2", "TV Globo", 2021),
        NovelaEntry("Um Lugar ao Sol", "TV Globo", 2021),
        NovelaEntry("Quanto Mais Vida, Melhor!", "TV Globo", 2021),
        NovelaEntry("Além da Ilusão", "TV Globo", 2022),
        NovelaEntry("Pantanal", "TV Globo", 2022),
        NovelaEntry("Cara e Coragem", "TV Globo", 2022),
        NovelaEntry("Mar do Sertão", "TV Globo", 2022),
        NovelaEntry("Travessia", "TV Globo", 2022),
        NovelaEntry("Todas as Flores", "TV Globo", 2022),
        NovelaEntry("Vai na Fé", "TV Globo", 2023),
        NovelaEntry("Amor Perfeito", "TV Globo", 2023),
        NovelaEntry("Terra e Paixão", "TV Globo", 2023),
        NovelaEntry("Fuzuê", "TV Globo", 2023),
        NovelaEntry("Elas por Elas", "TV Globo", 2023),
        NovelaEntry("Renascer", "TV Globo", 2024),
        NovelaEntry("Família É Tudo", "TV Globo", 2024),
        NovelaEntry("No Rancho Fundo", "TV Globo", 2024),
        NovelaEntry("Mania de Você", "TV Globo", 2024),
        NovelaEntry("Volta por Cima", "TV Globo", 2024),
        NovelaEntry("Garota do Momento", "TV Globo", 2024),
        NovelaEntry("Vale Tudo", "TV Globo", 2025),
        NovelaEntry("Dona de Mim", "TV Globo", 2025),
        NovelaEntry("Guerreiros do Sol", "TV Globo", 2025),
        NovelaEntry("Êta Mundo Melhor!", "TV Globo", 2025),
        NovelaEntry("Três Graças", "TV Globo", 2025),
        NovelaEntry("Coração Acelerado", "TV Globo", 2026),
        NovelaEntry("A Nobreza do Amor", "TV Globo", 2026),
        NovelaEntry("Quem Ama Cuida", "TV Globo", 2026),
        NovelaEntry("A Próxima Página e Terra da Garoa", "TV Globo", 2026),

    )

    /** All distinct broadcaster names represented in the catalog. */
    val networks: List<String> by lazy { entries.map { it.network }.distinct() }

    /** Lowercase, accent-stripped, punctuation-stripped form used for matching. */
    fun normalize(input: String): String {
        val noAccents = Normalizer.normalize(input, Normalizer.Form.NFD)
            .replace(Regex("\\p{M}"), "")
        return noAccents.lowercase(Locale.ROOT)
            .replace(Regex("[^a-z0-9 ]"), " ")
            .replace(Regex("\\s+"), " ")
            .trim()
    }

    private val normalizedIndex: Map<String, NovelaEntry> by lazy {
        // Last entry wins on collision (e.g. remakes sharing a title); rare in this dataset.
        entries.associateBy { normalize(it.title) }
    }

    /** True if [title] matches a known telenovela once normalised. */
    fun isKnownNovela(title: String): Boolean = normalizedIndex.containsKey(normalize(title))

    /** Returns the catalog entry matching [title], or null if not recognised. */
    fun find(title: String): NovelaEntry? = normalizedIndex[normalize(title)]
}
